### ISSUE TITLE
Upgrade jackson dependencies and publish a new beta

### ISSUE THREAD

**Issue by FlorianBruckner** [StripesFramework/stripes#79]
We're still maintaining a few applications using stripes framework and even started using the @RestActionBean from 1.7.0-beta4.

Unfortunately we're hit by a nasty dependency thing with jackson - the version used for compiling Stripes leads to a wrong execution path inside jackson. We can work around most parts (for example, by using our own version of JsonResolution which we've been using for some time now), but this fails for error handling:

```
Caused by: java.lang.ClassCastException: com.fasterxml.jackson.databind.ser.std.MapProperty cannot be cast to com.fasterxml.jackson.databind.ser.BeanPropertyWriter
	at com.fasterxml.jackson.databind.ser.impl.SimpleBeanPropertyFilter$1.serializeAsField(SimpleBeanPropertyFilter.java:93)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFilteredFields(MapSerializer.java:883)
	... 59 more

```

This specific exception could be avoided by compiling stripes with a newer version of jackson as dependency.

There are already PR for updating the dependencies that were automatically created by a bot, may I suggest to acccept those PRs and probably create a beta5 for then? 

If no one is up to doing this, I volounteer to doing it myself.

**Comment by mprins** [comment]
I started #71 in August 2018 but it didn't get any traction

**Comment by mprins** [comment]
also #78 , #77 and #76 are hitting an API incompatibility, eg: https://travis-ci.org/StripesFramework/stripes/builds/611234005#L6394-L6435
